import { MigrationInterface, QueryRunner } from "typeorm";

/**
 * The initial schema: 36 tables covering identity, media, the audit trail and
 * every content type the website renders.
 *
 * Generated from the entity definitions rather than hand-written, so the
 * schema and the code cannot describe different databases. Read it before
 * running it — that is the whole reason migrations exist here instead of
 * TypeORM's `synchronize`, which would apply a column rename as a drop and a
 * create and take the data with it.
 *
 * `down()` drops everything in reverse dependency order. It is correct, and it
 * is also a complete data loss on anything but an empty database.
 */

export class InitialSchema1790071086374 implements MigrationInterface {
    name = 'InitialSchema1790071086374'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE \`media_assets\` (\`id\` varchar(36) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`version\` int NOT NULL, \`storageKey\` varchar(512) NOT NULL, \`originalName\` varchar(255) NOT NULL, \`mimeType\` varchar(128) NOT NULL, \`size\` bigint UNSIGNED NOT NULL, \`width\` int UNSIGNED NULL, \`height\` int UNSIGNED NULL, \`blurDataUrl\` text NULL, \`alt\` varchar(320) NOT NULL DEFAULT '', \`caption\` varchar(512) NULL, \`purpose\` enum ('CASE_STUDY_CAPTURE', 'CASE_STUDY_MOBILE', 'TEAM_PORTRAIT', 'CLIENT_LOGO', 'PARTNER_LOGO', 'INDUSTRY_COVER', 'POST_HERO', 'TESTIMONIAL_AVATAR', 'OFFICE_FLAG', 'TECH_LOGO', 'GENERAL') NOT NULL DEFAULT 'GENERAL', \`driver\` enum ('LOCAL', 'S3') NOT NULL DEFAULT 'LOCAL', \`checksum\` char(64) NOT NULL, \`uploadedById\` varchar(36) NULL, INDEX \`IDX_5b6be5d790ea4e21a5c096a157\` (\`deletedAt\`), UNIQUE INDEX \`IDX_1f6db84f73f8458960c18f9901\` (\`storageKey\`), UNIQUE INDEX \`idx_media_checksum_purpose\` (\`checksum\`, \`purpose\`), INDEX \`idx_media_purpose\` (\`purpose\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`refresh_tokens\` (\`id\` varchar(36) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`version\` int NOT NULL, \`tokenHash\` char(64) NOT NULL, \`sessionId\` char(36) NOT NULL, \`userId\` varchar(36) NOT NULL, \`expiresAt\` datetime(6) NOT NULL, \`revokedAt\` datetime(6) NULL, \`replacedByTokenId\` char(36) NULL, \`ipAddress\` varchar(45) NULL, \`userAgent\` varchar(512) NULL, \`device\` varchar(128) NULL, INDEX \`IDX_64d94d81cd444af0313b47fab4\` (\`deletedAt\`), UNIQUE INDEX \`IDX_c25bc63d248ca90e8dcc1d92d0\` (\`tokenHash\`), INDEX \`IDX_b25a58a00578bd1b7a01623d2d\` (\`sessionId\`), INDEX \`IDX_610102b60fea1455310ccd299d\` (\`userId\`), INDEX \`idx_refresh_user_active\` (\`userId\`, \`revokedAt\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`roles\` (\`id\` varchar(36) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`version\` int NOT NULL, \`name\` enum ('SUPER_ADMIN', 'ADMIN', 'EDITOR') NOT NULL, \`description\` varchar(255) NOT NULL, INDEX \`IDX_e72912af85f8ca6ac65522f71e\` (\`deletedAt\`), UNIQUE INDEX \`IDX_648e3f5447f725579d7d4ffdfb\` (\`name\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`permissions\` (\`id\` varchar(36) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`version\` int NOT NULL, \`name\` varchar(64) NOT NULL, \`description\` varchar(255) NOT NULL, INDEX \`IDX_7a0dec7dfde2c5c743fdadf9ba\` (\`deletedAt\`), UNIQUE INDEX \`IDX_48ce552495d14eae9b187bb671\` (\`name\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`users\` (\`id\` varchar(36) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`version\` int NOT NULL, \`username\` varchar(64) NOT NULL, \`email\` varchar(255) NOT NULL, \`fullName\` varchar(160) NOT NULL, \`passwordHash\` varchar(255) NOT NULL, \`tokenVersion\` int NOT NULL DEFAULT '0', \`isActive\` tinyint NOT NULL DEFAULT 1, \`mustChangePassword\` tinyint NOT NULL DEFAULT 0, \`failedLoginAttempts\` int NOT NULL DEFAULT '0', \`lockedUntil\` datetime(6) NULL, \`lastLoginAt\` datetime(6) NULL, \`lastLoginIp\` varchar(45) NULL, \`passwordChangedAt\` datetime(6) NULL, \`avatarId\` varchar(36) NULL, INDEX \`IDX_2a32f641edba1d0f973c19cc94\` (\`deletedAt\`), UNIQUE INDEX \`IDX_fe0bb3f6520ee0469504521e71\` (\`username\`), UNIQUE INDEX \`IDX_97672ac88f789774dd47f7c8be\` (\`email\`), INDEX \`idx_users_active\` (\`isActive\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`audit_logs\` (\`id\` varchar(36) NOT NULL, \`action\` enum ('LOGIN_SUCCESS', 'LOGIN_FAILED', 'LOGOUT', 'TOKEN_REFRESH', 'PASSWORD_CHANGED', 'ACCOUNT_LOCKED', 'CREATE', 'UPDATE', 'DELETE', 'RESTORE', 'PUBLISH', 'UNPUBLISH', 'REORDER', 'MEDIA_UPLOAD', 'MEDIA_DELETE', 'USER_CREATED', 'USER_UPDATED', 'USER_DISABLED', 'REVALIDATE') NOT NULL, \`resource\` enum ('auth', 'user', 'case_study', 'case_study_section', 'service', 'industry', 'office', 'post', 'leader', 'team_member', 'client', 'partner', 'testimonial', 'technology', 'stat', 'social_link', 'media', 'setting') NOT NULL, \`resourceId\` char(36) NULL, \`resourceLabel\` varchar(255) NULL, \`actorId\` char(36) NULL, \`actorUsername\` varchar(64) NULL, \`ipAddress\` varchar(45) NULL, \`userAgent\` varchar(512) NULL, \`device\` varchar(128) NULL, \`country\` char(2) NULL, \`requestId\` char(64) NULL, \`method\` varchar(10) NULL, \`path\` varchar(512) NULL, \`statusCode\` int UNSIGNED NULL, \`durationMs\` int UNSIGNED NULL, \`changes\` json NULL, \`reason\` varchar(255) NULL, \`success\` tinyint NOT NULL DEFAULT 1, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), INDEX \`IDX_a3efbfd507134492f264a19b9c\` (\`requestId\`), INDEX \`IDX_c69efb19bf127c97e6740ad530\` (\`createdAt\`), INDEX \`idx_audit_ip_time\` (\`ipAddress\`, \`createdAt\`), INDEX \`idx_audit_action_time\` (\`action\`, \`createdAt\`), INDEX \`idx_audit_resource\` (\`resource\`, \`resourceId\`), INDEX \`idx_audit_actor_time\` (\`actorId\`, \`createdAt\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`login_attempts\` (\`id\` varchar(36) NOT NULL, \`identifier\` varchar(255) NOT NULL, \`ipAddress\` varchar(45) NOT NULL, \`userAgent\` varchar(512) NULL, \`success\` tinyint NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), INDEX \`idx_login_ip_time\` (\`ipAddress\`, \`createdAt\`), INDEX \`idx_login_identifier_time\` (\`identifier\`, \`createdAt\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`industries\` (\`id\` varchar(36) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`version\` int NOT NULL, \`status\` enum ('DRAFT', 'PUBLISHED', 'ARCHIVED') NOT NULL DEFAULT 'DRAFT', \`publishedAt\` datetime(6) NULL, \`position\` int NOT NULL DEFAULT '0', \`updatedById\` char(36) NULL, \`slug\` varchar(140) NOT NULL, \`name\` varchar(160) NOT NULL, \`description\` varchar(320) NOT NULL, \`proof\` varchar(255) NOT NULL DEFAULT '', \`imageId\` varchar(36) NULL, \`seoTitle\` varchar(180) NULL, \`seoDescription\` varchar(320) NULL, \`seoOgimageid\` char(36) NULL, \`seoCanonicalurl\` varchar(512) NULL, \`seoNoindex\` tinyint NOT NULL DEFAULT 0, INDEX \`IDX_b37d7b03c194fc3f7959fa9a72\` (\`deletedAt\`), INDEX \`IDX_7cd44bc02590f3bcc9c1632960\` (\`status\`), INDEX \`IDX_35827fa46c863a11e7a3a65f57\` (\`position\`), UNIQUE INDEX \`IDX_4ff129e4d52b3a32e131fa21fd\` (\`slug\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`services\` (\`id\` varchar(36) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`version\` int NOT NULL, \`status\` enum ('DRAFT', 'PUBLISHED', 'ARCHIVED') NOT NULL DEFAULT 'DRAFT', \`publishedAt\` datetime(6) NULL, \`position\` int NOT NULL DEFAULT '0', \`updatedById\` char(36) NULL, \`slug\` varchar(140) NOT NULL, \`number\` char(2) NOT NULL, \`title\` varchar(255) NOT NULL, \`group\` enum ('tech', 'gbs') NOT NULL, \`phase\` enum ('Build', 'Automate', 'Operate') NOT NULL, \`icon\` varchar(64) NOT NULL, \`summary\` text NOT NULL, \`seoTitle\` varchar(180) NULL, \`seoDescription\` varchar(320) NULL, \`seoOgimageid\` char(36) NULL, \`seoCanonicalurl\` varchar(512) NULL, \`seoNoindex\` tinyint NOT NULL DEFAULT 0, INDEX \`IDX_aed5131855b365a0bf34674d05\` (\`deletedAt\`), INDEX \`IDX_8acaf7b489ffd8187b5cdd504c\` (\`status\`), INDEX \`IDX_5cb0938408594496bcc9bf870e\` (\`position\`), UNIQUE INDEX \`IDX_02cf0d0f46e11d22d952f62367\` (\`slug\`), INDEX \`idx_service_group_position\` (\`group\`, \`position\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`service_subs\` (\`id\` varchar(36) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`version\` int NOT NULL, \`serviceId\` varchar(36) NOT NULL, \`title\` varchar(255) NOT NULL, \`description\` text NOT NULL, \`position\` int NOT NULL DEFAULT '0', INDEX \`IDX_5baf2c7cddb5e5f31c76117dcb\` (\`deletedAt\`), INDEX \`idx_service_sub_order\` (\`serviceId\`, \`position\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`case_studies\` (\`id\` varchar(36) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`version\` int NOT NULL, \`status\` enum ('DRAFT', 'PUBLISHED', 'ARCHIVED') NOT NULL DEFAULT 'DRAFT', \`publishedAt\` datetime(6) NULL, \`position\` int NOT NULL DEFAULT '0', \`updatedById\` char(36) NULL, \`slug\` varchar(140) NOT NULL, \`title\` varchar(255) NOT NULL, \`tagline\` varchar(320) NOT NULL, \`sector\` varchar(120) NOT NULL, \`phase\` enum ('Build', 'Automate', 'Operate') NOT NULL, \`surface\` enum ('site', 'app') NOT NULL DEFAULT 'app', \`frame\` enum ('laptop', 'window') NOT NULL DEFAULT 'window', \`summary\` text NOT NULL, \`client\` varchar(160) NULL, \`team\` varchar(120) NULL, \`featured\` tinyint NOT NULL DEFAULT 0, \`introHeading\` varchar(255) NOT NULL DEFAULT '', \`challengesLead\` text NULL, \`resultsLead\` text NULL, \`imageId\` varchar(36) NULL, \`mobileImageId\` varchar(36) NULL, \`seoTitle\` varchar(180) NULL, \`seoDescription\` varchar(320) NULL, \`seoOgimageid\` char(36) NULL, \`seoCanonicalurl\` varchar(512) NULL, \`seoNoindex\` tinyint NOT NULL DEFAULT 0, INDEX \`IDX_5b55381e8b8d66d521198d11c1\` (\`deletedAt\`), INDEX \`IDX_f59ade872913764418a4fd43f7\` (\`status\`), INDEX \`IDX_55b87ece0dd7318a9258ac23ba\` (\`position\`), UNIQUE INDEX \`IDX_257998c57ee734fa61666e6242\` (\`slug\`), INDEX \`IDX_586f87069f239eeaf261133f68\` (\`featured\`), INDEX \`idx_case_study_phase\` (\`phase\`), INDEX \`idx_case_study_featured\` (\`featured\`, \`position\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`case_study_capabilities\` (\`id\` varchar(36) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`version\` int NOT NULL, \`caseStudyId\` varchar(36) NOT NULL, \`label\` varchar(160) NOT NULL, \`position\` int NOT NULL DEFAULT '0', INDEX \`IDX_d8abd0b805792fa2c663871962\` (\`deletedAt\`), UNIQUE INDEX \`idx_cs_capability_unique\` (\`caseStudyId\`, \`label\`), INDEX \`idx_cs_capability_order\` (\`caseStudyId\`, \`position\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`case_study_callouts\` (\`id\` varchar(36) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`version\` int NOT NULL, \`caseStudyId\` varchar(36) NOT NULL, \`capabilityId\` varchar(36) NOT NULL, \`icon\` varchar(64) NOT NULL, \`x\` decimal(5,4) NOT NULL, \`y\` decimal(5,4) NOT NULL, \`position\` int NOT NULL DEFAULT '0', INDEX \`IDX_3fd431ab734bc8c4aa985ee445\` (\`deletedAt\`), INDEX \`idx_cs_callout_order\` (\`caseStudyId\`, \`position\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`case_study_highlights\` (\`id\` varchar(36) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`version\` int NOT NULL, \`caseStudyId\` varchar(36) NOT NULL, \`value\` varchar(80) NOT NULL, \`detail\` varchar(160) NOT NULL, \`position\` int NOT NULL DEFAULT '0', INDEX \`IDX_9cbc399619a61e919e60a87186\` (\`deletedAt\`), INDEX \`idx_cs_highlight_order\` (\`caseStudyId\`, \`position\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`case_study_stats\` (\`id\` varchar(36) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`version\` int NOT NULL, \`caseStudyId\` varchar(36) NOT NULL, \`value\` varchar(80) NOT NULL, \`label\` varchar(160) NOT NULL, \`position\` int NOT NULL DEFAULT '0', INDEX \`IDX_6da0a30ebbb3cd4d8043bc1312\` (\`deletedAt\`), INDEX \`idx_cs_stat_order\` (\`caseStudyId\`, \`position\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`case_study_meta_rows\` (\`id\` varchar(36) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`version\` int NOT NULL, \`caseStudyId\` varchar(36) NOT NULL, \`label\` varchar(80) NOT NULL, \`value\` text NOT NULL, \`position\` int NOT NULL DEFAULT '0', INDEX \`IDX_1d6f96a67af40426b0375abe22\` (\`deletedAt\`), INDEX \`idx_cs_meta_order\` (\`caseStudyId\`, \`position\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`case_study_paragraphs\` (\`id\` varchar(36) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`version\` int NOT NULL, \`caseStudyId\` varchar(36) NOT NULL, \`kind\` enum ('INTRO', 'RESULT') NOT NULL, \`text\` text NOT NULL, \`position\` int NOT NULL DEFAULT '0', INDEX \`IDX_3ebf9c2351232802c9f0a79d19\` (\`deletedAt\`), INDEX \`idx_cs_paragraph_order\` (\`caseStudyId\`, \`kind\`, \`position\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`case_study_challenges\` (\`id\` varchar(36) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`version\` int NOT NULL, \`caseStudyId\` varchar(36) NOT NULL, \`title\` varchar(255) NOT NULL, \`challenge\` text NOT NULL, \`solution\` text NOT NULL, \`position\` int NOT NULL DEFAULT '0', INDEX \`IDX_0464a61d41ef7b782f1c16c878\` (\`deletedAt\`), INDEX \`idx_cs_challenge_order\` (\`caseStudyId\`, \`position\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`case_study_screenshots\` (\`id\` varchar(36) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`version\` int NOT NULL, \`caseStudyId\` varchar(36) NOT NULL, \`mediaId\` varchar(36) NOT NULL, \`fit\` enum ('cover', 'contain') NOT NULL DEFAULT 'cover', \`lead\` tinyint NOT NULL DEFAULT 0, \`position\` int NOT NULL DEFAULT '0', INDEX \`IDX_fa7857b9ce7faf03f3b7daa485\` (\`deletedAt\`), INDEX \`idx_cs_shot_order\` (\`caseStudyId\`, \`position\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`posts\` (\`id\` varchar(36) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`version\` int NOT NULL, \`status\` enum ('DRAFT', 'PUBLISHED', 'ARCHIVED') NOT NULL DEFAULT 'DRAFT', \`publishedAt\` datetime(6) NULL, \`position\` int NOT NULL DEFAULT '0', \`updatedById\` char(36) NULL, \`slug\` varchar(160) NOT NULL, \`kind\` enum ('Blog', 'News', 'Case Note') NOT NULL DEFAULT 'Blog', \`title\` varchar(255) NOT NULL, \`excerpt\` text NOT NULL, \`body\` longtext NULL, \`displayDate\` date NULL, \`imageId\` varchar(36) NULL, \`externalUrl\` varchar(512) NULL, \`featured\` tinyint NOT NULL DEFAULT 0, \`readingMinutes\` int UNSIGNED NULL, \`seoTitle\` varchar(180) NULL, \`seoDescription\` varchar(320) NULL, \`seoOgimageid\` char(36) NULL, \`seoCanonicalurl\` varchar(512) NULL, \`seoNoindex\` tinyint NOT NULL DEFAULT 0, INDEX \`IDX_2fdceba3d316f92cf224ba56fa\` (\`deletedAt\`), INDEX \`IDX_a69d9e2ae78ef7d100f8317ae0\` (\`status\`), INDEX \`IDX_862deee3599ab1a65f8d6a4845\` (\`position\`), UNIQUE INDEX \`IDX_54ddf9075260407dcfdd724857\` (\`slug\`), INDEX \`idx_post_featured\` (\`featured\`), INDEX \`idx_post_kind_position\` (\`kind\`, \`position\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`offices\` (\`id\` varchar(36) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`version\` int NOT NULL, \`status\` enum ('DRAFT', 'PUBLISHED', 'ARCHIVED') NOT NULL DEFAULT 'DRAFT', \`publishedAt\` datetime(6) NULL, \`position\` int NOT NULL DEFAULT '0', \`updatedById\` char(36) NULL, \`slug\` varchar(140) NOT NULL, \`country\` varchar(120) NOT NULL, \`city\` varchar(120) NOT NULL, \`role\` varchar(160) NOT NULL, \`blurb\` varchar(320) NOT NULL, \`flagId\` varchar(36) NULL, \`longitude\` decimal(9,6) NOT NULL, \`latitude\` decimal(8,6) NOT NULL, \`isHeadquarters\` tinyint NOT NULL DEFAULT 0, \`email\` varchar(255) NULL, \`phone\` varchar(64) NULL, INDEX \`IDX_f631d07cc9a03cc06dc96e3060\` (\`deletedAt\`), INDEX \`IDX_769b5cb9e02bc3c68ee629e319\` (\`status\`), INDEX \`IDX_152b954669d5878edecc39e27c\` (\`position\`), UNIQUE INDEX \`IDX_ba72b57939b356681e784fd9ae\` (\`slug\`), UNIQUE INDEX \`IDX_22d4c547586f49da580094e3ff\` (\`city\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`office_address_lines\` (\`id\` varchar(36) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`version\` int NOT NULL, \`officeId\` varchar(36) NOT NULL, \`text\` varchar(255) NOT NULL, \`position\` int NOT NULL DEFAULT '0', INDEX \`IDX_bf1d491121092fb7812565d37b\` (\`deletedAt\`), INDEX \`idx_office_line_order\` (\`officeId\`, \`position\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`delivery_countries\` (\`id\` varchar(36) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`version\` int NOT NULL, \`status\` enum ('DRAFT', 'PUBLISHED', 'ARCHIVED') NOT NULL DEFAULT 'DRAFT', \`publishedAt\` datetime(6) NULL, \`position\` int NOT NULL DEFAULT '0', \`updatedById\` char(36) NULL, \`name\` varchar(120) NOT NULL, \`code\` char(2) NOT NULL, INDEX \`IDX_aea537ed6129e5127e069fd8aa\` (\`deletedAt\`), INDEX \`IDX_3253a8159236f50ded965f0a5a\` (\`status\`), INDEX \`IDX_04baab35dfe00b0b62692e9e47\` (\`position\`), UNIQUE INDEX \`IDX_0f087c5f364fa257b6098a827a\` (\`name\`), UNIQUE INDEX \`IDX_5f8af0b784857129fc92ace523\` (\`code\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`leaders\` (\`id\` varchar(36) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`version\` int NOT NULL, \`status\` enum ('DRAFT', 'PUBLISHED', 'ARCHIVED') NOT NULL DEFAULT 'DRAFT', \`publishedAt\` datetime(6) NULL, \`position\` int NOT NULL DEFAULT '0', \`updatedById\` char(36) NULL, \`slug\` varchar(140) NOT NULL, \`name\` varchar(160) NOT NULL, \`role\` varchar(160) NOT NULL, \`initials\` varchar(4) NOT NULL, \`photoId\` varchar(36) NULL, \`bio\` text NULL, \`email\` varchar(255) NULL, \`linkedinUrl\` varchar(512) NULL, \`isFounder\` tinyint NOT NULL DEFAULT 0, \`isCoFounder\` tinyint NOT NULL DEFAULT 0, INDEX \`IDX_dcb3b534788fe87c5664585170\` (\`deletedAt\`), INDEX \`IDX_43945a4942adcceec731342893\` (\`status\`), INDEX \`IDX_e8021b06d2cbd368276031c854\` (\`position\`), UNIQUE INDEX \`IDX_74266cc18b5895f68805b7b189\` (\`slug\`), INDEX \`idx_leader_founder\` (\`isFounder\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`leader_points\` (\`id\` varchar(36) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`version\` int NOT NULL, \`leaderId\` varchar(36) NOT NULL, \`text\` varchar(255) NOT NULL, \`position\` int NOT NULL DEFAULT '0', INDEX \`IDX_02df6d053fad8e800a0db620e9\` (\`deletedAt\`), INDEX \`idx_leader_point_order\` (\`leaderId\`, \`position\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`team_members\` (\`id\` varchar(36) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`version\` int NOT NULL, \`status\` enum ('DRAFT', 'PUBLISHED', 'ARCHIVED') NOT NULL DEFAULT 'DRAFT', \`publishedAt\` datetime(6) NULL, \`position\` int NOT NULL DEFAULT '0', \`updatedById\` char(36) NULL, \`slug\` varchar(140) NOT NULL, \`name\` varchar(160) NOT NULL, \`role\` varchar(160) NOT NULL, \`department\` varchar(120) NULL, \`initials\` varchar(4) NOT NULL, \`photoId\` varchar(36) NULL, \`bio\` text NULL, \`linkedinUrl\` varchar(512) NULL, \`officeId\` varchar(36) NULL, INDEX \`IDX_b68893492887628b31887179c2\` (\`deletedAt\`), INDEX \`IDX_c34b9e412f78f6fd9139a55424\` (\`status\`), INDEX \`IDX_703e027ffc3ea62f236a23fab4\` (\`position\`), UNIQUE INDEX \`IDX_a3f55af63bfe54cc9b6f641c6e\` (\`slug\`), INDEX \`idx_team_department\` (\`department\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`testimonials\` (\`id\` varchar(36) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`version\` int NOT NULL, \`status\` enum ('DRAFT', 'PUBLISHED', 'ARCHIVED') NOT NULL DEFAULT 'DRAFT', \`publishedAt\` datetime(6) NULL, \`position\` int NOT NULL DEFAULT '0', \`updatedById\` char(36) NULL, \`quote\` text NOT NULL, \`author\` varchar(160) NOT NULL, \`role\` varchar(160) NOT NULL, \`company\` varchar(160) NOT NULL, \`avatarId\` varchar(36) NULL, \`pending\` tinyint NOT NULL DEFAULT 1, INDEX \`IDX_407437c7127b36d9ac3d49d6a9\` (\`deletedAt\`), INDEX \`IDX_ab097b9ae4c8e443cf58b9281c\` (\`status\`), INDEX \`IDX_6a19523f317460bb97b4a9cc45\` (\`position\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`clients\` (\`id\` varchar(36) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`version\` int NOT NULL, \`status\` enum ('DRAFT', 'PUBLISHED', 'ARCHIVED') NOT NULL DEFAULT 'DRAFT', \`publishedAt\` datetime(6) NULL, \`position\` int NOT NULL DEFAULT '0', \`updatedById\` char(36) NULL, \`slug\` varchar(140) NOT NULL, \`name\` varchar(200) NOT NULL, \`logoId\` varchar(36) NULL, \`websiteUrl\` varchar(512) NULL, \`isPartner\` tinyint NOT NULL DEFAULT 0, INDEX \`IDX_d63530bef84b2da69599ad7b4e\` (\`deletedAt\`), INDEX \`IDX_8468e296bc86338b10e1db1a77\` (\`status\`), INDEX \`IDX_4b242f087f37e1a38b490e84a3\` (\`position\`), UNIQUE INDEX \`IDX_2a850b0972b11500683fe49b3c\` (\`slug\`), INDEX \`idx_client_partner_position\` (\`isPartner\`, \`position\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`technologies\` (\`id\` varchar(36) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`version\` int NOT NULL, \`status\` enum ('DRAFT', 'PUBLISHED', 'ARCHIVED') NOT NULL DEFAULT 'DRAFT', \`publishedAt\` datetime(6) NULL, \`position\` int NOT NULL DEFAULT '0', \`updatedById\` char(36) NULL, \`slug\` varchar(140) NOT NULL, \`name\` varchar(120) NOT NULL, \`category\` varchar(80) NOT NULL, \`iconSlug\` varchar(80) NULL, \`logoId\` varchar(36) NULL, INDEX \`IDX_e5bffd997969f0a9a5cede0f23\` (\`deletedAt\`), INDEX \`IDX_53f31c56ce539dd346bd278dc8\` (\`status\`), INDEX \`IDX_2ae5be53984d02f1e87fb3811a\` (\`position\`), UNIQUE INDEX \`IDX_e1b296cd0df9807f28db43bcab\` (\`slug\`), INDEX \`idx_tech_category_position\` (\`category\`, \`position\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`stats\` (\`id\` varchar(36) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`version\` int NOT NULL, \`status\` enum ('DRAFT', 'PUBLISHED', 'ARCHIVED') NOT NULL DEFAULT 'DRAFT', \`publishedAt\` datetime(6) NULL, \`position\` int NOT NULL DEFAULT '0', \`updatedById\` char(36) NULL, \`key\` varchar(80) NOT NULL, \`value\` varchar(40) NOT NULL, \`label\` varchar(160) NOT NULL, \`group\` varchar(40) NOT NULL DEFAULT 'about', INDEX \`IDX_d045042998ad287c972cbc050c\` (\`deletedAt\`), INDEX \`IDX_7904b270357e6a9db8b765642b\` (\`status\`), INDEX \`IDX_a817adaacb665d143bf6eb5a1c\` (\`position\`), UNIQUE INDEX \`IDX_37c9b8e8e11378010e88350524\` (\`key\`), INDEX \`idx_stat_group_position\` (\`group\`, \`position\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`social_links\` (\`id\` varchar(36) NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`deletedAt\` datetime(6) NULL, \`version\` int NOT NULL, \`status\` enum ('DRAFT', 'PUBLISHED', 'ARCHIVED') NOT NULL DEFAULT 'DRAFT', \`publishedAt\` datetime(6) NULL, \`position\` int NOT NULL DEFAULT '0', \`updatedById\` char(36) NULL, \`label\` varchar(80) NOT NULL, \`url\` varchar(512) NOT NULL, \`icon\` varchar(64) NOT NULL, INDEX \`IDX_f1968f9170dc495b2504169b83\` (\`deletedAt\`), INDEX \`IDX_f2d7fa484a3326d1fce43ba7e9\` (\`status\`), INDEX \`IDX_bb7436a7a2c953bd8ffcdad366\` (\`position\`), UNIQUE INDEX \`IDX_0f41adf5dad8002b1eb6124296\` (\`label\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`settings\` (\`id\` varchar(36) NOT NULL, \`key\` varchar(120) NOT NULL, \`value\` text NOT NULL, \`valueType\` enum ('string', 'number', 'boolean', 'json') NOT NULL DEFAULT 'string', \`group\` varchar(60) NOT NULL DEFAULT 'general', \`description\` varchar(255) NULL, \`updatedById\` char(36) NULL, \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`IDX_c8639b7626fa94ba8265628f21\` (\`key\`), INDEX \`idx_setting_group\` (\`group\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`role_permissions\` (\`role_id\` varchar(36) NOT NULL, \`permission_id\` varchar(36) NOT NULL, INDEX \`IDX_178199805b901ccd220ab7740e\` (\`role_id\`), INDEX \`IDX_17022daf3f885f7d35423e9971\` (\`permission_id\`), PRIMARY KEY (\`role_id\`, \`permission_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`user_roles\` (\`user_id\` varchar(36) NOT NULL, \`role_id\` varchar(36) NOT NULL, INDEX \`IDX_87b8888186ca9769c960e92687\` (\`user_id\`), INDEX \`IDX_b23c65e50a758245a33ee35fda\` (\`role_id\`), PRIMARY KEY (\`user_id\`, \`role_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`service_case_studies\` (\`service_id\` varchar(36) NOT NULL, \`case_study_id\` varchar(36) NOT NULL, INDEX \`IDX_45d6eb9ca03f2d46d26126af4b\` (\`service_id\`), INDEX \`IDX_5b70912efb117732242ffed991\` (\`case_study_id\`), PRIMARY KEY (\`service_id\`, \`case_study_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`case_study_industries\` (\`case_study_id\` varchar(36) NOT NULL, \`industry_id\` varchar(36) NOT NULL, INDEX \`IDX_b41e6133fe9f44a1cc656366c0\` (\`case_study_id\`), INDEX \`IDX_a60a33b0ca51dec34993bb1b76\` (\`industry_id\`), PRIMARY KEY (\`case_study_id\`, \`industry_id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`media_assets\` ADD CONSTRAINT \`FK_81809341c22bc61384738e8c80b\` FOREIGN KEY (\`uploadedById\`) REFERENCES \`users\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`refresh_tokens\` ADD CONSTRAINT \`FK_610102b60fea1455310ccd299de\` FOREIGN KEY (\`userId\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`users\` ADD CONSTRAINT \`FK_3e1f52ec904aed992472f2be147\` FOREIGN KEY (\`avatarId\`) REFERENCES \`media_assets\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`industries\` ADD CONSTRAINT \`FK_3ac5ad3f95c371da541f3cccd30\` FOREIGN KEY (\`imageId\`) REFERENCES \`media_assets\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`service_subs\` ADD CONSTRAINT \`FK_c21e7aafed917e38b9efbcdc15f\` FOREIGN KEY (\`serviceId\`) REFERENCES \`services\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`case_studies\` ADD CONSTRAINT \`FK_9fcc3d51f53d26c11f29b381832\` FOREIGN KEY (\`imageId\`) REFERENCES \`media_assets\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`case_studies\` ADD CONSTRAINT \`FK_0846c10ebf823788af5a0b31527\` FOREIGN KEY (\`mobileImageId\`) REFERENCES \`media_assets\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`case_study_capabilities\` ADD CONSTRAINT \`FK_8b0d5401a67b5e73215ae8b4558\` FOREIGN KEY (\`caseStudyId\`) REFERENCES \`case_studies\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`case_study_callouts\` ADD CONSTRAINT \`FK_4bf7f2060a454d8e827aedb5656\` FOREIGN KEY (\`caseStudyId\`) REFERENCES \`case_studies\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`case_study_callouts\` ADD CONSTRAINT \`FK_aa65b2b1e06dddf00d233b13e20\` FOREIGN KEY (\`capabilityId\`) REFERENCES \`case_study_capabilities\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`case_study_highlights\` ADD CONSTRAINT \`FK_1bfe668ea00c1a730f9ddd75ce8\` FOREIGN KEY (\`caseStudyId\`) REFERENCES \`case_studies\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`case_study_stats\` ADD CONSTRAINT \`FK_230573f4a388cf3cde92f561a98\` FOREIGN KEY (\`caseStudyId\`) REFERENCES \`case_studies\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`case_study_meta_rows\` ADD CONSTRAINT \`FK_31a40c348d6b44035690c12b6db\` FOREIGN KEY (\`caseStudyId\`) REFERENCES \`case_studies\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`case_study_paragraphs\` ADD CONSTRAINT \`FK_4623b41656d74759198dbc020d3\` FOREIGN KEY (\`caseStudyId\`) REFERENCES \`case_studies\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`case_study_challenges\` ADD CONSTRAINT \`FK_8c1ea7af2df0e3eba8a04ba9394\` FOREIGN KEY (\`caseStudyId\`) REFERENCES \`case_studies\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`case_study_screenshots\` ADD CONSTRAINT \`FK_e4f619b991d1f82077fe1dfb7d9\` FOREIGN KEY (\`caseStudyId\`) REFERENCES \`case_studies\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`case_study_screenshots\` ADD CONSTRAINT \`FK_e93d4b9ae3f753a197a707e1674\` FOREIGN KEY (\`mediaId\`) REFERENCES \`media_assets\`(\`id\`) ON DELETE RESTRICT ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`posts\` ADD CONSTRAINT \`FK_294625b251f17eca44cc57fbeb8\` FOREIGN KEY (\`imageId\`) REFERENCES \`media_assets\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`offices\` ADD CONSTRAINT \`FK_6869adb807307f0fae1564a9e1b\` FOREIGN KEY (\`flagId\`) REFERENCES \`media_assets\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`office_address_lines\` ADD CONSTRAINT \`FK_91f79a7ff0903e887e30a5bafcd\` FOREIGN KEY (\`officeId\`) REFERENCES \`offices\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`leaders\` ADD CONSTRAINT \`FK_0e63ffce2b25fbe7e88f18a6d08\` FOREIGN KEY (\`photoId\`) REFERENCES \`media_assets\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`leader_points\` ADD CONSTRAINT \`FK_6f4d381c025fc1ce86c889b6fb1\` FOREIGN KEY (\`leaderId\`) REFERENCES \`leaders\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`team_members\` ADD CONSTRAINT \`FK_fb9c79083c166751a3da2a71270\` FOREIGN KEY (\`photoId\`) REFERENCES \`media_assets\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`team_members\` ADD CONSTRAINT \`FK_dfc2fb8ffa36119879b9d18e504\` FOREIGN KEY (\`officeId\`) REFERENCES \`offices\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`testimonials\` ADD CONSTRAINT \`FK_b286bad5d4ba0efdafb34a585fc\` FOREIGN KEY (\`avatarId\`) REFERENCES \`media_assets\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`clients\` ADD CONSTRAINT \`FK_1ec04ce2c40f6f68b57386a03e3\` FOREIGN KEY (\`logoId\`) REFERENCES \`media_assets\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`technologies\` ADD CONSTRAINT \`FK_79ecfbddb2cbf819debdcba8665\` FOREIGN KEY (\`logoId\`) REFERENCES \`media_assets\`(\`id\`) ON DELETE SET NULL ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`role_permissions\` ADD CONSTRAINT \`FK_178199805b901ccd220ab7740ec\` FOREIGN KEY (\`role_id\`) REFERENCES \`roles\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`role_permissions\` ADD CONSTRAINT \`FK_17022daf3f885f7d35423e9971e\` FOREIGN KEY (\`permission_id\`) REFERENCES \`permissions\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`user_roles\` ADD CONSTRAINT \`FK_87b8888186ca9769c960e926870\` FOREIGN KEY (\`user_id\`) REFERENCES \`users\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`user_roles\` ADD CONSTRAINT \`FK_b23c65e50a758245a33ee35fda1\` FOREIGN KEY (\`role_id\`) REFERENCES \`roles\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`service_case_studies\` ADD CONSTRAINT \`FK_45d6eb9ca03f2d46d26126af4b5\` FOREIGN KEY (\`service_id\`) REFERENCES \`services\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`service_case_studies\` ADD CONSTRAINT \`FK_5b70912efb117732242ffed991b\` FOREIGN KEY (\`case_study_id\`) REFERENCES \`case_studies\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`case_study_industries\` ADD CONSTRAINT \`FK_b41e6133fe9f44a1cc656366c01\` FOREIGN KEY (\`case_study_id\`) REFERENCES \`case_studies\`(\`id\`) ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE \`case_study_industries\` ADD CONSTRAINT \`FK_a60a33b0ca51dec34993bb1b769\` FOREIGN KEY (\`industry_id\`) REFERENCES \`industries\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`case_study_industries\` DROP FOREIGN KEY \`FK_a60a33b0ca51dec34993bb1b769\``);
        await queryRunner.query(`ALTER TABLE \`case_study_industries\` DROP FOREIGN KEY \`FK_b41e6133fe9f44a1cc656366c01\``);
        await queryRunner.query(`ALTER TABLE \`service_case_studies\` DROP FOREIGN KEY \`FK_5b70912efb117732242ffed991b\``);
        await queryRunner.query(`ALTER TABLE \`service_case_studies\` DROP FOREIGN KEY \`FK_45d6eb9ca03f2d46d26126af4b5\``);
        await queryRunner.query(`ALTER TABLE \`user_roles\` DROP FOREIGN KEY \`FK_b23c65e50a758245a33ee35fda1\``);
        await queryRunner.query(`ALTER TABLE \`user_roles\` DROP FOREIGN KEY \`FK_87b8888186ca9769c960e926870\``);
        await queryRunner.query(`ALTER TABLE \`role_permissions\` DROP FOREIGN KEY \`FK_17022daf3f885f7d35423e9971e\``);
        await queryRunner.query(`ALTER TABLE \`role_permissions\` DROP FOREIGN KEY \`FK_178199805b901ccd220ab7740ec\``);
        await queryRunner.query(`ALTER TABLE \`technologies\` DROP FOREIGN KEY \`FK_79ecfbddb2cbf819debdcba8665\``);
        await queryRunner.query(`ALTER TABLE \`clients\` DROP FOREIGN KEY \`FK_1ec04ce2c40f6f68b57386a03e3\``);
        await queryRunner.query(`ALTER TABLE \`testimonials\` DROP FOREIGN KEY \`FK_b286bad5d4ba0efdafb34a585fc\``);
        await queryRunner.query(`ALTER TABLE \`team_members\` DROP FOREIGN KEY \`FK_dfc2fb8ffa36119879b9d18e504\``);
        await queryRunner.query(`ALTER TABLE \`team_members\` DROP FOREIGN KEY \`FK_fb9c79083c166751a3da2a71270\``);
        await queryRunner.query(`ALTER TABLE \`leader_points\` DROP FOREIGN KEY \`FK_6f4d381c025fc1ce86c889b6fb1\``);
        await queryRunner.query(`ALTER TABLE \`leaders\` DROP FOREIGN KEY \`FK_0e63ffce2b25fbe7e88f18a6d08\``);
        await queryRunner.query(`ALTER TABLE \`office_address_lines\` DROP FOREIGN KEY \`FK_91f79a7ff0903e887e30a5bafcd\``);
        await queryRunner.query(`ALTER TABLE \`offices\` DROP FOREIGN KEY \`FK_6869adb807307f0fae1564a9e1b\``);
        await queryRunner.query(`ALTER TABLE \`posts\` DROP FOREIGN KEY \`FK_294625b251f17eca44cc57fbeb8\``);
        await queryRunner.query(`ALTER TABLE \`case_study_screenshots\` DROP FOREIGN KEY \`FK_e93d4b9ae3f753a197a707e1674\``);
        await queryRunner.query(`ALTER TABLE \`case_study_screenshots\` DROP FOREIGN KEY \`FK_e4f619b991d1f82077fe1dfb7d9\``);
        await queryRunner.query(`ALTER TABLE \`case_study_challenges\` DROP FOREIGN KEY \`FK_8c1ea7af2df0e3eba8a04ba9394\``);
        await queryRunner.query(`ALTER TABLE \`case_study_paragraphs\` DROP FOREIGN KEY \`FK_4623b41656d74759198dbc020d3\``);
        await queryRunner.query(`ALTER TABLE \`case_study_meta_rows\` DROP FOREIGN KEY \`FK_31a40c348d6b44035690c12b6db\``);
        await queryRunner.query(`ALTER TABLE \`case_study_stats\` DROP FOREIGN KEY \`FK_230573f4a388cf3cde92f561a98\``);
        await queryRunner.query(`ALTER TABLE \`case_study_highlights\` DROP FOREIGN KEY \`FK_1bfe668ea00c1a730f9ddd75ce8\``);
        await queryRunner.query(`ALTER TABLE \`case_study_callouts\` DROP FOREIGN KEY \`FK_aa65b2b1e06dddf00d233b13e20\``);
        await queryRunner.query(`ALTER TABLE \`case_study_callouts\` DROP FOREIGN KEY \`FK_4bf7f2060a454d8e827aedb5656\``);
        await queryRunner.query(`ALTER TABLE \`case_study_capabilities\` DROP FOREIGN KEY \`FK_8b0d5401a67b5e73215ae8b4558\``);
        await queryRunner.query(`ALTER TABLE \`case_studies\` DROP FOREIGN KEY \`FK_0846c10ebf823788af5a0b31527\``);
        await queryRunner.query(`ALTER TABLE \`case_studies\` DROP FOREIGN KEY \`FK_9fcc3d51f53d26c11f29b381832\``);
        await queryRunner.query(`ALTER TABLE \`service_subs\` DROP FOREIGN KEY \`FK_c21e7aafed917e38b9efbcdc15f\``);
        await queryRunner.query(`ALTER TABLE \`industries\` DROP FOREIGN KEY \`FK_3ac5ad3f95c371da541f3cccd30\``);
        await queryRunner.query(`ALTER TABLE \`users\` DROP FOREIGN KEY \`FK_3e1f52ec904aed992472f2be147\``);
        await queryRunner.query(`ALTER TABLE \`refresh_tokens\` DROP FOREIGN KEY \`FK_610102b60fea1455310ccd299de\``);
        await queryRunner.query(`ALTER TABLE \`media_assets\` DROP FOREIGN KEY \`FK_81809341c22bc61384738e8c80b\``);
        await queryRunner.query(`DROP INDEX \`IDX_a60a33b0ca51dec34993bb1b76\` ON \`case_study_industries\``);
        await queryRunner.query(`DROP INDEX \`IDX_b41e6133fe9f44a1cc656366c0\` ON \`case_study_industries\``);
        await queryRunner.query(`DROP TABLE \`case_study_industries\``);
        await queryRunner.query(`DROP INDEX \`IDX_5b70912efb117732242ffed991\` ON \`service_case_studies\``);
        await queryRunner.query(`DROP INDEX \`IDX_45d6eb9ca03f2d46d26126af4b\` ON \`service_case_studies\``);
        await queryRunner.query(`DROP TABLE \`service_case_studies\``);
        await queryRunner.query(`DROP INDEX \`IDX_b23c65e50a758245a33ee35fda\` ON \`user_roles\``);
        await queryRunner.query(`DROP INDEX \`IDX_87b8888186ca9769c960e92687\` ON \`user_roles\``);
        await queryRunner.query(`DROP TABLE \`user_roles\``);
        await queryRunner.query(`DROP INDEX \`IDX_17022daf3f885f7d35423e9971\` ON \`role_permissions\``);
        await queryRunner.query(`DROP INDEX \`IDX_178199805b901ccd220ab7740e\` ON \`role_permissions\``);
        await queryRunner.query(`DROP TABLE \`role_permissions\``);
        await queryRunner.query(`DROP INDEX \`idx_setting_group\` ON \`settings\``);
        await queryRunner.query(`DROP INDEX \`IDX_c8639b7626fa94ba8265628f21\` ON \`settings\``);
        await queryRunner.query(`DROP TABLE \`settings\``);
        await queryRunner.query(`DROP INDEX \`IDX_0f41adf5dad8002b1eb6124296\` ON \`social_links\``);
        await queryRunner.query(`DROP INDEX \`IDX_bb7436a7a2c953bd8ffcdad366\` ON \`social_links\``);
        await queryRunner.query(`DROP INDEX \`IDX_f2d7fa484a3326d1fce43ba7e9\` ON \`social_links\``);
        await queryRunner.query(`DROP INDEX \`IDX_f1968f9170dc495b2504169b83\` ON \`social_links\``);
        await queryRunner.query(`DROP TABLE \`social_links\``);
        await queryRunner.query(`DROP INDEX \`idx_stat_group_position\` ON \`stats\``);
        await queryRunner.query(`DROP INDEX \`IDX_37c9b8e8e11378010e88350524\` ON \`stats\``);
        await queryRunner.query(`DROP INDEX \`IDX_a817adaacb665d143bf6eb5a1c\` ON \`stats\``);
        await queryRunner.query(`DROP INDEX \`IDX_7904b270357e6a9db8b765642b\` ON \`stats\``);
        await queryRunner.query(`DROP INDEX \`IDX_d045042998ad287c972cbc050c\` ON \`stats\``);
        await queryRunner.query(`DROP TABLE \`stats\``);
        await queryRunner.query(`DROP INDEX \`idx_tech_category_position\` ON \`technologies\``);
        await queryRunner.query(`DROP INDEX \`IDX_e1b296cd0df9807f28db43bcab\` ON \`technologies\``);
        await queryRunner.query(`DROP INDEX \`IDX_2ae5be53984d02f1e87fb3811a\` ON \`technologies\``);
        await queryRunner.query(`DROP INDEX \`IDX_53f31c56ce539dd346bd278dc8\` ON \`technologies\``);
        await queryRunner.query(`DROP INDEX \`IDX_e5bffd997969f0a9a5cede0f23\` ON \`technologies\``);
        await queryRunner.query(`DROP TABLE \`technologies\``);
        await queryRunner.query(`DROP INDEX \`idx_client_partner_position\` ON \`clients\``);
        await queryRunner.query(`DROP INDEX \`IDX_2a850b0972b11500683fe49b3c\` ON \`clients\``);
        await queryRunner.query(`DROP INDEX \`IDX_4b242f087f37e1a38b490e84a3\` ON \`clients\``);
        await queryRunner.query(`DROP INDEX \`IDX_8468e296bc86338b10e1db1a77\` ON \`clients\``);
        await queryRunner.query(`DROP INDEX \`IDX_d63530bef84b2da69599ad7b4e\` ON \`clients\``);
        await queryRunner.query(`DROP TABLE \`clients\``);
        await queryRunner.query(`DROP INDEX \`IDX_6a19523f317460bb97b4a9cc45\` ON \`testimonials\``);
        await queryRunner.query(`DROP INDEX \`IDX_ab097b9ae4c8e443cf58b9281c\` ON \`testimonials\``);
        await queryRunner.query(`DROP INDEX \`IDX_407437c7127b36d9ac3d49d6a9\` ON \`testimonials\``);
        await queryRunner.query(`DROP TABLE \`testimonials\``);
        await queryRunner.query(`DROP INDEX \`idx_team_department\` ON \`team_members\``);
        await queryRunner.query(`DROP INDEX \`IDX_a3f55af63bfe54cc9b6f641c6e\` ON \`team_members\``);
        await queryRunner.query(`DROP INDEX \`IDX_703e027ffc3ea62f236a23fab4\` ON \`team_members\``);
        await queryRunner.query(`DROP INDEX \`IDX_c34b9e412f78f6fd9139a55424\` ON \`team_members\``);
        await queryRunner.query(`DROP INDEX \`IDX_b68893492887628b31887179c2\` ON \`team_members\``);
        await queryRunner.query(`DROP TABLE \`team_members\``);
        await queryRunner.query(`DROP INDEX \`idx_leader_point_order\` ON \`leader_points\``);
        await queryRunner.query(`DROP INDEX \`IDX_02df6d053fad8e800a0db620e9\` ON \`leader_points\``);
        await queryRunner.query(`DROP TABLE \`leader_points\``);
        await queryRunner.query(`DROP INDEX \`idx_leader_founder\` ON \`leaders\``);
        await queryRunner.query(`DROP INDEX \`IDX_74266cc18b5895f68805b7b189\` ON \`leaders\``);
        await queryRunner.query(`DROP INDEX \`IDX_e8021b06d2cbd368276031c854\` ON \`leaders\``);
        await queryRunner.query(`DROP INDEX \`IDX_43945a4942adcceec731342893\` ON \`leaders\``);
        await queryRunner.query(`DROP INDEX \`IDX_dcb3b534788fe87c5664585170\` ON \`leaders\``);
        await queryRunner.query(`DROP TABLE \`leaders\``);
        await queryRunner.query(`DROP INDEX \`IDX_5f8af0b784857129fc92ace523\` ON \`delivery_countries\``);
        await queryRunner.query(`DROP INDEX \`IDX_0f087c5f364fa257b6098a827a\` ON \`delivery_countries\``);
        await queryRunner.query(`DROP INDEX \`IDX_04baab35dfe00b0b62692e9e47\` ON \`delivery_countries\``);
        await queryRunner.query(`DROP INDEX \`IDX_3253a8159236f50ded965f0a5a\` ON \`delivery_countries\``);
        await queryRunner.query(`DROP INDEX \`IDX_aea537ed6129e5127e069fd8aa\` ON \`delivery_countries\``);
        await queryRunner.query(`DROP TABLE \`delivery_countries\``);
        await queryRunner.query(`DROP INDEX \`idx_office_line_order\` ON \`office_address_lines\``);
        await queryRunner.query(`DROP INDEX \`IDX_bf1d491121092fb7812565d37b\` ON \`office_address_lines\``);
        await queryRunner.query(`DROP TABLE \`office_address_lines\``);
        await queryRunner.query(`DROP INDEX \`IDX_22d4c547586f49da580094e3ff\` ON \`offices\``);
        await queryRunner.query(`DROP INDEX \`IDX_ba72b57939b356681e784fd9ae\` ON \`offices\``);
        await queryRunner.query(`DROP INDEX \`IDX_152b954669d5878edecc39e27c\` ON \`offices\``);
        await queryRunner.query(`DROP INDEX \`IDX_769b5cb9e02bc3c68ee629e319\` ON \`offices\``);
        await queryRunner.query(`DROP INDEX \`IDX_f631d07cc9a03cc06dc96e3060\` ON \`offices\``);
        await queryRunner.query(`DROP TABLE \`offices\``);
        await queryRunner.query(`DROP INDEX \`idx_post_kind_position\` ON \`posts\``);
        await queryRunner.query(`DROP INDEX \`idx_post_featured\` ON \`posts\``);
        await queryRunner.query(`DROP INDEX \`IDX_54ddf9075260407dcfdd724857\` ON \`posts\``);
        await queryRunner.query(`DROP INDEX \`IDX_862deee3599ab1a65f8d6a4845\` ON \`posts\``);
        await queryRunner.query(`DROP INDEX \`IDX_a69d9e2ae78ef7d100f8317ae0\` ON \`posts\``);
        await queryRunner.query(`DROP INDEX \`IDX_2fdceba3d316f92cf224ba56fa\` ON \`posts\``);
        await queryRunner.query(`DROP TABLE \`posts\``);
        await queryRunner.query(`DROP INDEX \`idx_cs_shot_order\` ON \`case_study_screenshots\``);
        await queryRunner.query(`DROP INDEX \`IDX_fa7857b9ce7faf03f3b7daa485\` ON \`case_study_screenshots\``);
        await queryRunner.query(`DROP TABLE \`case_study_screenshots\``);
        await queryRunner.query(`DROP INDEX \`idx_cs_challenge_order\` ON \`case_study_challenges\``);
        await queryRunner.query(`DROP INDEX \`IDX_0464a61d41ef7b782f1c16c878\` ON \`case_study_challenges\``);
        await queryRunner.query(`DROP TABLE \`case_study_challenges\``);
        await queryRunner.query(`DROP INDEX \`idx_cs_paragraph_order\` ON \`case_study_paragraphs\``);
        await queryRunner.query(`DROP INDEX \`IDX_3ebf9c2351232802c9f0a79d19\` ON \`case_study_paragraphs\``);
        await queryRunner.query(`DROP TABLE \`case_study_paragraphs\``);
        await queryRunner.query(`DROP INDEX \`idx_cs_meta_order\` ON \`case_study_meta_rows\``);
        await queryRunner.query(`DROP INDEX \`IDX_1d6f96a67af40426b0375abe22\` ON \`case_study_meta_rows\``);
        await queryRunner.query(`DROP TABLE \`case_study_meta_rows\``);
        await queryRunner.query(`DROP INDEX \`idx_cs_stat_order\` ON \`case_study_stats\``);
        await queryRunner.query(`DROP INDEX \`IDX_6da0a30ebbb3cd4d8043bc1312\` ON \`case_study_stats\``);
        await queryRunner.query(`DROP TABLE \`case_study_stats\``);
        await queryRunner.query(`DROP INDEX \`idx_cs_highlight_order\` ON \`case_study_highlights\``);
        await queryRunner.query(`DROP INDEX \`IDX_9cbc399619a61e919e60a87186\` ON \`case_study_highlights\``);
        await queryRunner.query(`DROP TABLE \`case_study_highlights\``);
        await queryRunner.query(`DROP INDEX \`idx_cs_callout_order\` ON \`case_study_callouts\``);
        await queryRunner.query(`DROP INDEX \`IDX_3fd431ab734bc8c4aa985ee445\` ON \`case_study_callouts\``);
        await queryRunner.query(`DROP TABLE \`case_study_callouts\``);
        await queryRunner.query(`DROP INDEX \`idx_cs_capability_order\` ON \`case_study_capabilities\``);
        await queryRunner.query(`DROP INDEX \`idx_cs_capability_unique\` ON \`case_study_capabilities\``);
        await queryRunner.query(`DROP INDEX \`IDX_d8abd0b805792fa2c663871962\` ON \`case_study_capabilities\``);
        await queryRunner.query(`DROP TABLE \`case_study_capabilities\``);
        await queryRunner.query(`DROP INDEX \`idx_case_study_featured\` ON \`case_studies\``);
        await queryRunner.query(`DROP INDEX \`idx_case_study_phase\` ON \`case_studies\``);
        await queryRunner.query(`DROP INDEX \`IDX_586f87069f239eeaf261133f68\` ON \`case_studies\``);
        await queryRunner.query(`DROP INDEX \`IDX_257998c57ee734fa61666e6242\` ON \`case_studies\``);
        await queryRunner.query(`DROP INDEX \`IDX_55b87ece0dd7318a9258ac23ba\` ON \`case_studies\``);
        await queryRunner.query(`DROP INDEX \`IDX_f59ade872913764418a4fd43f7\` ON \`case_studies\``);
        await queryRunner.query(`DROP INDEX \`IDX_5b55381e8b8d66d521198d11c1\` ON \`case_studies\``);
        await queryRunner.query(`DROP TABLE \`case_studies\``);
        await queryRunner.query(`DROP INDEX \`idx_service_sub_order\` ON \`service_subs\``);
        await queryRunner.query(`DROP INDEX \`IDX_5baf2c7cddb5e5f31c76117dcb\` ON \`service_subs\``);
        await queryRunner.query(`DROP TABLE \`service_subs\``);
        await queryRunner.query(`DROP INDEX \`idx_service_group_position\` ON \`services\``);
        await queryRunner.query(`DROP INDEX \`IDX_02cf0d0f46e11d22d952f62367\` ON \`services\``);
        await queryRunner.query(`DROP INDEX \`IDX_5cb0938408594496bcc9bf870e\` ON \`services\``);
        await queryRunner.query(`DROP INDEX \`IDX_8acaf7b489ffd8187b5cdd504c\` ON \`services\``);
        await queryRunner.query(`DROP INDEX \`IDX_aed5131855b365a0bf34674d05\` ON \`services\``);
        await queryRunner.query(`DROP TABLE \`services\``);
        await queryRunner.query(`DROP INDEX \`IDX_4ff129e4d52b3a32e131fa21fd\` ON \`industries\``);
        await queryRunner.query(`DROP INDEX \`IDX_35827fa46c863a11e7a3a65f57\` ON \`industries\``);
        await queryRunner.query(`DROP INDEX \`IDX_7cd44bc02590f3bcc9c1632960\` ON \`industries\``);
        await queryRunner.query(`DROP INDEX \`IDX_b37d7b03c194fc3f7959fa9a72\` ON \`industries\``);
        await queryRunner.query(`DROP TABLE \`industries\``);
        await queryRunner.query(`DROP INDEX \`idx_login_identifier_time\` ON \`login_attempts\``);
        await queryRunner.query(`DROP INDEX \`idx_login_ip_time\` ON \`login_attempts\``);
        await queryRunner.query(`DROP TABLE \`login_attempts\``);
        await queryRunner.query(`DROP INDEX \`idx_audit_actor_time\` ON \`audit_logs\``);
        await queryRunner.query(`DROP INDEX \`idx_audit_resource\` ON \`audit_logs\``);
        await queryRunner.query(`DROP INDEX \`idx_audit_action_time\` ON \`audit_logs\``);
        await queryRunner.query(`DROP INDEX \`idx_audit_ip_time\` ON \`audit_logs\``);
        await queryRunner.query(`DROP INDEX \`IDX_c69efb19bf127c97e6740ad530\` ON \`audit_logs\``);
        await queryRunner.query(`DROP INDEX \`IDX_a3efbfd507134492f264a19b9c\` ON \`audit_logs\``);
        await queryRunner.query(`DROP TABLE \`audit_logs\``);
        await queryRunner.query(`DROP INDEX \`idx_users_active\` ON \`users\``);
        await queryRunner.query(`DROP INDEX \`IDX_97672ac88f789774dd47f7c8be\` ON \`users\``);
        await queryRunner.query(`DROP INDEX \`IDX_fe0bb3f6520ee0469504521e71\` ON \`users\``);
        await queryRunner.query(`DROP INDEX \`IDX_2a32f641edba1d0f973c19cc94\` ON \`users\``);
        await queryRunner.query(`DROP TABLE \`users\``);
        await queryRunner.query(`DROP INDEX \`IDX_48ce552495d14eae9b187bb671\` ON \`permissions\``);
        await queryRunner.query(`DROP INDEX \`IDX_7a0dec7dfde2c5c743fdadf9ba\` ON \`permissions\``);
        await queryRunner.query(`DROP TABLE \`permissions\``);
        await queryRunner.query(`DROP INDEX \`IDX_648e3f5447f725579d7d4ffdfb\` ON \`roles\``);
        await queryRunner.query(`DROP INDEX \`IDX_e72912af85f8ca6ac65522f71e\` ON \`roles\``);
        await queryRunner.query(`DROP TABLE \`roles\``);
        await queryRunner.query(`DROP INDEX \`idx_refresh_user_active\` ON \`refresh_tokens\``);
        await queryRunner.query(`DROP INDEX \`IDX_610102b60fea1455310ccd299d\` ON \`refresh_tokens\``);
        await queryRunner.query(`DROP INDEX \`IDX_b25a58a00578bd1b7a01623d2d\` ON \`refresh_tokens\``);
        await queryRunner.query(`DROP INDEX \`IDX_c25bc63d248ca90e8dcc1d92d0\` ON \`refresh_tokens\``);
        await queryRunner.query(`DROP INDEX \`IDX_64d94d81cd444af0313b47fab4\` ON \`refresh_tokens\``);
        await queryRunner.query(`DROP TABLE \`refresh_tokens\``);
        await queryRunner.query(`DROP INDEX \`idx_media_purpose\` ON \`media_assets\``);
        await queryRunner.query(`DROP INDEX \`idx_media_checksum_purpose\` ON \`media_assets\``);
        await queryRunner.query(`DROP INDEX \`IDX_1f6db84f73f8458960c18f9901\` ON \`media_assets\``);
        await queryRunner.query(`DROP INDEX \`IDX_5b6be5d790ea4e21a5c096a157\` ON \`media_assets\``);
        await queryRunner.query(`DROP TABLE \`media_assets\``);
    }

}
