/**
 * The technologies an industry's detail page runs in its strip, keyed by slug.
 *
 * Every name comes from the company stack in `TechStack` and resolves to real
 * artwork through `TechIcon` — no monograms, which read as gaps in a moving
 * strip. Where a case study filed under the industry names its stack (the
 * "Technologies" meta row), those lead: Azure AI Search and LangChain for
 * financial services, Elasticsearch for media, TensorFlow, Keras and Blender
 * for commerce, VR headsets for healthcare and education.
 *
 * Fourteen or more per industry, so one pass of the marquee is wider than the
 * frame and the loop never shows its seam.
 *
 * An industry without an entry shows no strip.
 */
export const INDUSTRY_TECHNOLOGIES: Record<string, string[]> = {
  healthcare: [
    "AWS",
    "Azure",
    "Python",
    "FastAPI",
    "React",
    "React Native",
    "Flutter",
    "PostgreSQL",
    "MongoDB",
    "OpenAI",
    "LangChain",
    "TensorFlow",
    "PyTorch",
    "Unity",
    "Meta Quest",
  ],
  "financial-services": [
    "Azure AI Search",
    "LangChain",
    "OpenAI",
    "Anthropic Claude",
    "Elasticsearch",
    "Azure",
    "AWS",
    "Python",
    "NestJS",
    "React",
    "PostgreSQL",
    "Redis",
    "Ethereum",
    "Solidity",
    "Chainlink",
  ],
  media: [
    "Elasticsearch",
    "AWS",
    "React",
    "Next.js",
    "Angular",
    "React Native",
    "Node.js",
    "TensorFlow",
    "Keras",
    "PyTorch",
    "OpenAI",
    "Blender",
    "MongoDB",
    "Redis",
    "Docker",
  ],
  government: [
    "Azure",
    "AWS",
    "React",
    "Angular",
    "NestJS",
    "Node.js",
    "PostgreSQL",
    "Elasticsearch",
    "OpenAI",
    "Python",
    "Kubernetes",
    "Docker",
    "Terraform",
    "Grafana",
  ],
  "supply-chain": [
    "Azure",
    "AWS",
    "React",
    "React Native",
    "Flutter",
    "NestJS",
    "Node.js",
    "Python",
    "PostgreSQL",
    "MongoDB",
    "Redis",
    "n8n",
    "Zapier",
    "Kubernetes",
    "Grafana",
  ],
  manufacturing: [
    "Azure",
    "AWS",
    "Python",
    "PyTorch",
    "TensorFlow",
    "React",
    "React Native",
    "Node.js",
    "PostgreSQL",
    "Grafana",
    "Prometheus",
    "Docker",
    "Kubernetes",
    "Unity",
  ],
  "industrial-iot": [
    "AWS",
    "Azure",
    "GCP",
    "Python",
    "Go",
    "Node.js",
    "PyTorch",
    "TensorFlow",
    "React",
    "PostgreSQL",
    "Redis",
    "Grafana",
    "Prometheus",
    "Docker",
    "Kubernetes",
  ],
  education: [
    "React",
    "Next.js",
    "Vue.js",
    "React Native",
    "Flutter",
    "Node.js",
    "NestJS",
    "PostgreSQL",
    "MongoDB",
    "OpenAI",
    "LangChain",
    "Unity",
    "Meta Quest",
    "AWS",
  ],
  commerce: [
    "TensorFlow",
    "Keras",
    "Blender",
    "AWS",
    "Angular",
    "React Native",
    "React",
    "Next.js",
    "Node.js",
    "OpenAI",
    "PostgreSQL",
    "MongoDB",
    "Redis",
    "Docker",
  ],
  "enterprise-systems": [
    "Azure",
    "AWS",
    "GCP",
    "OpenAI",
    "Anthropic Claude",
    "Google Gemini",
    "LangChain",
    "Azure AI Search",
    "Python",
    "TypeScript",
    "NestJS",
    "React",
    "PostgreSQL",
    "Kubernetes",
    "Terraform",
  ],
  // The digital agriculture platform's stack: vision models for crop
  // diagnostics, an AI advisory engine, geospatial and satellite analytics,
  // and mobile apps that reach farmers in the field.
  agriculture: [
    "Python",
    "PyTorch",
    "TensorFlow",
    "Hugging Face",
    "OpenAI",
    "LangChain",
    "GCP",
    "AWS",
    "FastAPI",
    "React Native",
    "Flutter",
    "PostgreSQL",
    "MongoDB",
    "Grafana",
    "Docker",
  ],
};
