"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { animate, useReducedMotion } from "framer-motion";
import {
  BAND_OPACITY,
  camK,
  type Cam,
  dotPaths,
  GRAT,
  linePath,
  project,
  RINGS,
  ringPath,
} from "@/lib/globe-project";
import { OFFICES } from "@/lib/offices";
import { cn } from "@/lib/utils";

/* ---------------------------------------------------------------------------
   The delivery network, as the planet it runs on — and it turns.

   Geometry is real: `src/lib/globe-geometry.ts` is generated by
   `scripts/build-globe.mjs` from Natural Earth's 110m land layer. Everyone knows
   what this shape is meant to be, so a hand-drawn approximation would read as a
   mistake rather than as an abstraction.

   WHY THIS TURNS, rather than being a static picture with three pins on it.

   The offices are Lahore, San Jose and Dubai. Lahore and San Jose are 109.5°
   apart, and a globe only ever shows a 180° hemisphere — so from the resting
   camera (14°E/16°N, which puts Africa dead centre) San Jose is at depth -0.38:
   on the *far side of the planet*. There is no static camera that fixes this.
   The only view that carries all three sits at 83°N, looking straight down at
   the North Pole, which throws Africa onto the rim.

   So hovering an office turns the globe to face it and it settles back when you
   leave. Each office gets seen properly, dead centre, instead of squashed
   edge-on against the limb — and at rest the picture is unchanged.

   Only the Earth turns. The ripple floor is the ground it hangs over and the
   orbits are the space around it; both stay put, which is both physically right
   and free.
   --------------------------------------------------------------------------- */

/** The whole drawing's box. Wider than tall: the ripple plane spreads sideways. */
const VB = { w: 460, h: 420 };
/** Sphere, measured off the design reference: centre (1240,815) r=160 in a
    1536×1024 frame — so ~10.4% of frame width, sitting at 80.7%/79.6%. */
const G = { cx: 232, cy: 168, r: 138 };
/** Where the ripples sit: on the ground the globe hangs over. */
const PLANE = { cx: 232, cy: 296, ry: 0.3 };

const SCALE = G.r / 100;
/** Resting camera. Africa dead centre — the design reference's own view. */
const REST: Cam = { lon: 14, lat: 16 };

const EXPO = [0.19, 1, 0.22, 1] as const;

/** Everything the scene needs for one camera. Projection lives in
    `@/lib/globe-project` so the same code that renders here is what the
    verification script tests. */
function frameOf(cam: Cam) {
  const k = camK(cam);
  return {
    rings: RINGS.map((v) => ringPath(v, k)),
    grat: GRAT.map((v) => linePath(v, k)),
    dots: dotPaths(k),
    marks: OFFICES.map((o) => project(o.at.lon, o.at.lat, k)),
  };
}

/** The resting frame. Computed once, identical on server and client, so first
    paint is deterministic and hydration has nothing to disagree about. */
const REST_FRAME = frameOf(REST);

/** Shortest way round: from 14°E, San Jose is 135.9° WEST, not 224° east. Lerp
    the raw numbers and the globe spins the long way round the planet. */
function shortLon(from: number, to: number) {
  let d = to - from;
  while (d > 180) d -= 360;
  while (d < -180) d += 360;
  return d;
}

const HUE = { azure: "#449ED8", amber: "#F59F13" };

export default function Globe({ className }: { className?: string }) {
  const [hovered, setHovered] = useState<string | null>(null);
  const [pinned, setPinned] = useState<string | null>(null);
  const reduce = useReducedMotion();

  /* A click pins a country so it stays faced while you read it; hover still
     drives it otherwise. Same idiom the cards and the pyramid already share. */
  const shown = hovered ?? pinned;
  const office = OFFICES.find((o) => o.country === shown) ?? null;

  const svgRef = useRef<SVGSVGElement>(null);
  const markRef = useRef<(HTMLDivElement | null)[]>([]);
  const camRef = useRef<Cam>(REST);

  /* The scene is rendered ONCE and then driven imperatively. React must not own
     these attributes: re-rendering on every hover would snap `d` back to the
     resting frame mid-turn, and reconciling ~145 paths at 60fps is churn for a
     background motif. useMemo with no deps is what keeps React out of it. */
  const scene = useMemo(
    () => (
      <>
        {GRAT.map((_, i) => (
          <path
            key={`gr${i}`}
            data-grat
            d={REST_FRAME.grat[i]}
            stroke="#8FCAEB"
            strokeWidth={0.4 / SCALE}
            strokeOpacity="0.5"
          />
        ))}
        {RINGS.map((_, i) => (
          <path
            key={`ld${i}`}
            data-ring
            d={REST_FRAME.rings[i]}
            fill="#7FA6CC"
            fillOpacity="0.45"
            stroke="#5B87B5"
            strokeWidth={0.3 / SCALE}
            strokeOpacity="0.4"
          />
        ))}
        {BAND_OPACITY.map((op, i) => (
          <path
            key={`dt${i}`}
            data-dot
            d={REST_FRAME.dots[i]}
            fill="#2F5F8F"
            opacity={op}
          />
        ))}
      </>
    ),
    [],
  );

  /** Write one camera into the DOM. */
  const apply = (cam: Cam) => {
    const svg = svgRef.current;
    if (!svg) return;
    const k = camK(cam);
    const rings = svg.querySelectorAll<SVGPathElement>("[data-ring]");
    for (let i = 0; i < RINGS.length; i++)
      rings[i]?.setAttribute("d", ringPath(RINGS[i], k));
    const grat = svg.querySelectorAll<SVGPathElement>("[data-grat]");
    for (let i = 0; i < GRAT.length; i++)
      grat[i]?.setAttribute("d", linePath(GRAT[i], k));
    const dots = svg.querySelectorAll<SVGPathElement>("[data-dot]");
    const dp = dotPaths(k);
    for (let i = 0; i < dp.length; i++) dots[i]?.setAttribute("d", dp[i]);

    OFFICES.forEach((o, i) => {
      const el = markRef.current[i];
      if (!el) return;
      const p = project(o.at.lon, o.at.lat, k);
      // Marker positions are percentages of the SVG's own box, which is why the
      // wrapper has to BE that box — see the placement in CapabilitiesOS.
      el.style.left = `${((G.cx + (p.x - 100) * SCALE) / VB.w) * 100}%`;
      el.style.top = `${((G.cy + (p.y - 100) * SCALE) / VB.h) * 100}%`;
      el.style.opacity = p.z <= 0.02 ? "0" : String(Math.min(1, p.z * 2.2));
      el.style.pointerEvents = p.z > 0.15 ? "auto" : "none";
      el.style.transform = `translate(-50%,-50%) scale(${(0.72 + p.z * 0.28).toFixed(3)})`;
    });
  };

  useEffect(() => {
    const to: Cam = office ? { lon: office.at.lon, lat: office.at.lat } : REST;
    const from = camRef.current;
    const dLon = shortLon(from.lon, to.lon);
    const dLat = to.lat - from.lat;
    if (Math.abs(dLon) < 0.01 && Math.abs(dLat) < 0.01) return;

    // Reduced motion: still face the office, just don't perform the journey.
    if (reduce) {
      camRef.current = to;
      apply(to);
      return;
    }
    const ctrl = animate(0, 1, {
      duration: 0.85,
      ease: EXPO,
      onUpdate: (t) => {
        const cam = { lon: from.lon + dLon * t, lat: from.lat + dLat * t };
        camRef.current = cam;
        apply(cam);
      },
    });
    return () => ctrl.stop();
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [office, reduce]);

  return (
    <div className={className}>
      {/* The stage is the SVG's box and nothing else, so the markers — absolutely
          placed as a percentage of it — measure against the sphere's frame. The
          legend below is a sibling of the stage, not a child: put it inside and
          its height inflates the box the markers resolve against, dragging every
          pin off the planet. */}
      <div className="relative">
        <svg
          ref={svgRef}
          viewBox={`0 0 ${VB.w} ${VB.h}`}
          className="w-full"
          fill="none"
          aria-hidden
        >
          <defs>
            <radialGradient id="g-face" cx="38%" cy="30%" r="78%">
              <stop offset="0%" stopColor="#FFFFFF" />
              <stop offset="52%" stopColor="#EDF4FA" />
              <stop offset="100%" stopColor="#D3E2EF" />
            </radialGradient>
            {/* Fresnel: the limb is where a transparent sphere goes opaque. */}
            <radialGradient id="g-rim" cx="50%" cy="50%" r="50%">
              <stop offset="82%" stopColor="#449ED8" stopOpacity="0" />
              <stop offset="100%" stopColor="#449ED8" stopOpacity="0.3" />
            </radialGradient>
            {/* The globe dissolves into its own floor rather than stopping on a
              hard edge — an object in atmosphere, not a pasted circle. */}
            <linearGradient id="g-fade" x1="0" y1="0" x2="0" y2="1">
              <stop offset="0%" stopColor="#fff" stopOpacity="1" />
              <stop offset="66%" stopColor="#fff" stopOpacity="1" />
              <stop offset="100%" stopColor="#fff" stopOpacity="0.12" />
            </linearGradient>
            <mask id="g-mask">
              <rect width={VB.w} height={VB.h} fill="url(#g-fade)" />
            </mask>
            <radialGradient id="g-floor" cx="50%" cy="50%" r="50%">
              <stop offset="0%" stopColor="#fff" stopOpacity="0.9" />
              <stop offset="60%" stopColor="#fff" stopOpacity="0.5" />
              <stop offset="100%" stopColor="#fff" stopOpacity="0" />
            </radialGradient>
            <mask id="g-floor-mask">
              <ellipse
                cx={PLANE.cx}
                cy={PLANE.cy}
                rx={240}
                ry={80}
                fill="url(#g-floor)"
              />
            </mask>
            <clipPath id="g-clip">
              <circle cx={G.cx} cy={G.cy} r={G.r} />
            </clipPath>
          </defs>

          <g mask="url(#g-mask)">
            {/* Floor. Doesn't turn: it's the ground, not the planet. */}
            <g mask="url(#g-floor-mask)">
              {[58, 86, 116, 148, 182, 218].map((rx) => (
                <ellipse
                  key={rx}
                  cx={PLANE.cx}
                  cy={PLANE.cy}
                  rx={rx}
                  ry={rx * PLANE.ry}
                  stroke="#63696B"
                  strokeWidth="0.7"
                  strokeOpacity="0.5"
                  strokeDasharray="0.6 5.5"
                  strokeLinecap="round"
                />
              ))}
            </g>

            <circle cx={G.cx} cy={G.cy} r={G.r} fill="url(#g-face)" />

            {/* Earth, in the geometry's own 200×200 space.

              The clip and the transform must not sit on the same element: a
              `clip-path` resolves in the user space of the element that
              references it, which already includes that element's own
              transform. Put both here and the clip circle gets dragged along by
              the scale — it lands ~(414,262) instead of over the sphere, and
              most of the map disappears. Clip outside, place inside. */}
            <g clipPath="url(#g-clip)">
              <g
                transform={`translate(${G.cx} ${G.cy}) scale(${SCALE}) translate(-100 -100)`}
              >
                {scene}
              </g>
            </g>

            <circle cx={G.cx} cy={G.cy} r={G.r} fill="url(#g-rim)" />
            <circle
              cx={G.cx}
              cy={G.cy}
              r={G.r}
              stroke="#B9CDE0"
              strokeWidth="0.8"
              strokeOpacity="0.8"
            />

            {/* Orbits. Also don't turn: they're the space around the planet. */}
            {[
              { rx: 196, ry: 74, rot: -22, hex: HUE.azure, op: 0.5, w: 0.9 },
              { rx: 178, ry: 58, rot: 16, hex: HUE.amber, op: 0.42, w: 0.9 },
              { rx: 168, ry: 92, rot: -6, hex: HUE.azure, op: 0.26, w: 0.7 },
            ].map((o, i) => (
              <ellipse
                key={`or${i}`}
                cx={G.cx}
                cy={G.cy + 22}
                rx={o.rx}
                ry={o.ry}
                stroke={o.hex}
                strokeWidth={o.w}
                strokeOpacity={o.op}
                transform={`rotate(${o.rot} ${G.cx} ${G.cy + 22})`}
              />
            ))}
          </g>
        </svg>

        {/* Markers, as an HTML overlay rather than SVG hit-testing — the whole
          codebase positions interactive bits over a scene rather than putting
          pointer handlers on <g>/<circle>, and this inherits that. They're a
          duplicate of the legend below, which is the accessible interface, so
          they stay out of the tree for assistive tech. */}
        {OFFICES.map((o, i) => {
          const on = shown === o.country;
          return (
            <div
              key={o.country}
              aria-hidden
              ref={(el) => {
                markRef.current[i] = el;
              }}
              onMouseEnter={() => setHovered(o.country)}
              onMouseLeave={() => setHovered(null)}
              onClick={() =>
                setPinned((p) => (p === o.country ? null : o.country))
              }
              className="absolute z-10 cursor-pointer"
              style={{
                left: `${((G.cx + (REST_FRAME.marks[i].x - 100) * SCALE) / VB.w) * 100}%`,
                top: `${((G.cy + (REST_FRAME.marks[i].y - 100) * SCALE) / VB.h) * 100}%`,
                opacity:
                  REST_FRAME.marks[i].z <= 0.02
                    ? 0
                    : Math.min(1, REST_FRAME.marks[i].z * 2.2),
                pointerEvents: REST_FRAME.marks[i].z > 0.15 ? "auto" : "none",
                transform: "translate(-50%,-50%)",
              }}
            >
              {/* An oversized, invisible hit area around a small dot. */}
              <span className="absolute left-1/2 top-1/2 h-9 w-9 -translate-x-1/2 -translate-y-1/2" />
              <span
                className={cn(
                  "block h-[7px] w-[7px] rounded-full ring-2 transition-all duration-300 ease-expo",
                  on
                    ? "scale-[1.35] bg-amber ring-amber/25"
                    : "bg-azure ring-azure/20",
                )}
              />
              <span
                className={cn(
                  "absolute left-1/2 top-1/2 h-[7px] w-[7px] -translate-x-1/2 -translate-y-1/2 rounded-full transition-all duration-500 ease-expo",
                  on ? "scale-[3.4] bg-amber/20" : "scale-100 bg-transparent",
                )}
              />
            </div>
          );
        })}
      </div>

      {/* The legend. This is the real interface: a marker on the far side of the
          planet has nothing to hover, so the country has to be reachable from
          something that is always on screen. Focus feeds the same channel as
          hover, so it works from the keyboard. */}
      <ul className="mt-1 flex flex-wrap justify-end gap-1.5">
        {OFFICES.map((o) => {
          const on = shown === o.country;
          return (
            <li key={o.country}>
              <button
                type="button"
                onMouseEnter={() => setHovered(o.country)}
                onMouseLeave={() => setHovered(null)}
                onFocus={() => setHovered(o.country)}
                onBlur={() => setHovered(null)}
                onClick={() =>
                  setPinned((p) => (p === o.country ? null : o.country))
                }
                aria-pressed={pinned === o.country}
                className={cn(
                  "flex items-center gap-2 rounded-full border px-2.5 py-1.5 transition-colors duration-300 ease-expo",
                  on
                    ? "border-amber/40 bg-amber/[0.07]"
                    : "border-line bg-white/60 hover:border-line-strong",
                )}
              >
                {/* eslint-disable-next-line @next/next/no-img-element */}
                <img
                  src={o.flag}
                  alt=""
                  loading="lazy"
                  className="h-3 w-[18px] flex-none object-cover ring-1 ring-line-strong/70"
                />
                <span className="font-mono text-[9.5px] uppercase tracking-[0.14em] text-ink-500">
                  {o.country}
                </span>
                <span className="sr-only">— {o.role}</span>
              </button>
            </li>
          );
        })}
      </ul>
    </div>
  );
}
